---
# tasks file for ansible-preferences-server-data-loader

- include: install.yml
  tags:
    - install

- include: configure.yml
  tags:
    - configure

- include: deploy.yml
  tags:
    - deploy

- include: test.yml
  tags:
    - test
